server {
    listen       80;
    server_name  _;

    root   /usr/share/nginx/html;
    index  index.html;

    # Static assets: long cache.
    location /assets/ {
        access_log off;
        expires    30d;
        add_header Cache-Control "public, max-age=2592000, immutable";
    }

    # SPA fallback (HashRouter doesn't need it, but harmless).
    location / {
        try_files $uri $uri/ /index.html;
    }
}
